"use client";

import * as React from "react";
import type { Map as MapLibreMap } from "maplibre-gl";
import {
  ArrowDown,
  ArrowLeft,
  ArrowUp,
  ArrowUpDown,
  Calendar,
  ChevronRight,
  Columns3,
  Database,
  Hash,
  ImageOff,
  ImagePlus,
  LayoutGrid,
  Link2,
  List as ListIcon,
  MapPin,
  Scale,
  Search,
  Shapes,
  Sparkles,
  Table2,
  Tag,
  Trash2,
  TriangleAlert,
  Type,
  Upload,
  X,
} from "lucide-react";

import { Alert, AlertAction, AlertDescription, AlertTitle } from "@/registry/vianova/ui/alert";
import { Avatar, AvatarFallback, AvatarImage } from "@/registry/vianova/ui/avatar";
import { Badge } from "@/registry/vianova/ui/badge";
import { Button } from "@/registry/vianova/ui/button";
import {
  Empty,
  EmptyContent,
  EmptyDescription,
  EmptyHeader,
  EmptyMedia,
  EmptyTitle,
} from "@/registry/vianova/ui/empty";
import {
  InputGroup,
  InputGroupAddon,
  InputGroupInput,
} from "@/registry/vianova/ui/input-group";
import {
  Popover,
  PopoverContent,
  PopoverTrigger,
} from "@/registry/vianova/ui/popover";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/registry/vianova/ui/select";
import { Skeleton } from "@/registry/vianova/ui/skeleton";
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from "@/registry/vianova/ui/table";
import { Tabs, TabsList, TabsTrigger } from "@/registry/vianova/ui/tabs";
import { ToggleGroup, ToggleGroupItem } from "@/registry/vianova/ui/toggle-group";
import { Textarea } from "@/registry/vianova/ui/textarea";
import { ConfirmDialog } from "@/registry/vianova/patterns/confirm-dialog";
import { CategoryBadge } from "@/registry/vianova/product/category-badge";
import { LegendCategorical } from "@/registry/vianova/product/legend-categorical";
import { MapCanvas } from "@/registry/vianova/product/map-canvas";
import {
  useCategoryPointLayer,
  type CategoryPoint,
} from "@/registry/vianova/hooks/use-category-point-layer";
import {
  useCategoryShapeLayer,
  type CategoryShape,
} from "@/registry/vianova/hooks/use-category-shape-layer";
import { InlineEdit } from "@/registry/vianova/patterns/inline-edit";
import {
  CATEGORY_PALETTE,
  DEFAULT_LOGO_ZOOM,
  adviseLogo,
  badgeColor,
  prepareLogo,
  readStyleSet,
  resolveStyles,
  writeStyleSet,
  type CategoryStyle,
} from "@/registry/vianova/lib/category-style";
import { inferColumns, parseCsv, type ColumnType } from "@/registry/vianova/lib/csv";
import { useColorScheme } from "@/registry/vianova/hooks/use-color-scheme";
import { cn } from "@/registry/vianova/lib/utils";

/* -------------------------------------------------------------------------- */
/* Data                                                                        */
/* -------------------------------------------------------------------------- */

/**
 * Declared locally so this file compiles in a project without @types/node. The
 * expression must read `process.env.NEXT_PUBLIC_BASE_PATH` VERBATIM, because
 * Next substitutes that exact text at build time.
 */
declare const process: { env: Record<string, string | undefined> };

const BASE_PATH = process.env.NEXT_PUBLIC_BASE_PATH ?? "";
const WORKER_URL = `${BASE_PATH}/maplibre/maplibre-gl-worker.mjs`;

/**
 * The sample catalogue: fake Lisbon datasets for September 2026, each a CSV
 * fetched from the site rather than put in the JavaScript payload -- 700KB of
 * trips has no business in a page that may never open it. They are generated by
 * scripts/build-mds-trips.mjs, build-mds-infringements.mjs and
 * build-datahub-samples.mjs, which share their operators and geography, so the
 * datasets agree with one another.
 */
type SampleFeed = {
  /** The dataset's id. Category styles are saved under it, so other pages that
   * draw the same data (the map and reports workspaces) look it up by this. */
  id: string;
  file: string;
  section: Section;
  description: string;
  rowRepresents: string;
  domain: string;
  uploadedAt: string;
  dateRange?: [string, string];
  /** Regulations only. */
  status?: "active" | "inactive";
  units?: Record<string, string>;
};

const SAMPLE_FEEDS: SampleFeed[] = [
  {
    id: "sample-mds-lisbon",
    file: "mds-trips-lisbon.csv",
    section: "data",
    description:
      "Fake Mobility Data Specification trips for shared scooters and bikes in Lisbon, September 2026, from five operators.",
    rowRepresents: "a trip taken on a shared vehicle",
    domain: "micromobility",
    uploadedAt: "2026-10-01T09:00:00Z",
    dateRange: ["2026-09-01", "2026-09-30"],
    units: { trip_duration: "s", trip_distance: "m" },
  },
  {
    id: "sample-infringements-lisbon",
    file: "infringements-lisbon.csv",
    section: "data",
    description:
      "Fake parking infringements by shared scooters and bikes in Lisbon, September 2026: where a vehicle was left, what rule it broke and whether it was fined.",
    rowRepresents: "a parking infringement by a shared vehicle",
    domain: "micromobility",
    uploadedAt: "2026-10-02T09:00:00Z",
    dateRange: ["2026-09-01", "2026-09-30"],
    units: { fine_eur: "EUR" },
  },
  {
    id: "sample-mds-events-lisbon",
    file: "mds-events-lisbon.csv",
    section: "data",
    description:
      "Fake Mobility Data Specification vehicle events in Lisbon, September 2026: reservations, trip starts and ends, rebalancing, low batteries and maintenance.",
    rowRepresents: "a change in a vehicle's state",
    domain: "micromobility",
    uploadedAt: "2026-10-03T09:00:00Z",
    dateRange: ["2026-09-01", "2026-09-30"],
    units: { battery_pct: "%" },
  },
  {
    id: "sample-mds-vehicles-lisbon",
    file: "mds-vehicles-lisbon.csv",
    section: "data",
    description:
      "Fake snapshot of every shared vehicle in Lisbon at the end of September 2026: where it is, who runs it and whether it can be rented.",
    rowRepresents: "a shared vehicle",
    domain: "micromobility",
    uploadedAt: "2026-10-01T00:00:00Z",
    units: { battery_pct: "%" },
  },
  {
    id: "sample-parking-zones-lisbon",
    file: "parking-zones-lisbon.csv",
    section: "zones",
    description:
      "Fake parking bays, no-parking areas and slow zones for shared vehicles in Lisbon.",
    rowRepresents: "a zone",
    domain: "zones",
    uploadedAt: "2026-08-20T10:00:00Z",
    units: { speed_limit_kmh: "km/h" },
  },
  {
    id: "sample-districts-lisbon",
    file: "districts-lisbon.csv",
    section: "zones",
    description: "Fake outlines of twelve Lisbon neighbourhoods, with the kind of area each is.",
    rowRepresents: "a neighbourhood",
    domain: "zones",
    uploadedAt: "2026-07-14T10:00:00Z",
  },
  {
    id: "sample-regulation-speed-limit",
    file: "regulation-speed-limit-baixa.csv",
    section: "regulations",
    status: "active",
    description: "Fake 15 km/h limit for shared vehicles in the centre of Lisbon.",
    rowRepresents: "an area the rule covers",
    domain: "regulations",
    uploadedAt: "2026-02-20T09:00:00Z",
  },
  {
    id: "sample-regulation-no-parking",
    file: "regulation-no-parking-historic-centre.csv",
    section: "regulations",
    status: "active",
    description: "Fake parking restrictions in the historic centre: no parking, or bays only.",
    rowRepresents: "an area the rule covers",
    domain: "regulations",
    uploadedAt: "2026-01-10T09:00:00Z",
  },
  {
    id: "sample-regulation-fleet-cap",
    file: "regulation-fleet-cap-per-operator.csv",
    section: "regulations",
    status: "active",
    description: "Fake limit on how many vehicles each operator may leave in an area.",
    rowRepresents: "an operator's cap in an area",
    domain: "regulations",
    uploadedAt: "2026-05-18T09:00:00Z",
  },
  {
    id: "sample-regulation-night-curfew",
    file: "regulation-night-curfew-bairro-alto.csv",
    section: "regulations",
    status: "inactive",
    description: "Fake summer night curfew for shared vehicles around Bairro Alto. No longer in force.",
    rowRepresents: "an area the rule covers",
    domain: "regulations",
    uploadedAt: "2025-05-20T09:00:00Z",
  },
];

/** What each column of the samples means, so they read like real feeds. */
const SAMPLE_DESCRIPTIONS: Record<string, string> = {
  trip_id: "Unique identifier for the trip",
  provider_id: "Identifier of the operator that reported the record",
  provider_name: "Operator that runs the vehicle",
  device_id: "Identifier of the vehicle, stable across records",
  vehicle_type: "Kind of vehicle used",
  propulsion_types: "How the vehicle is powered",
  start_time: "When the trip started, in UTC",
  end_time: "When the trip ended, in UTC",
  trip_duration: "Length of the trip in seconds",
  trip_distance: "Distance travelled in metres",
  route: "Path taken, as a line of longitude and latitude points",
  infringement_id: "Unique identifier for the infringement",
  infringement_type: "The rule the vehicle broke",
  status: "Where the case stands: open, resolved or fined",
  fine_eur: "Amount fined, when the case ended in a fine",
  detected_at: "When the infringement was detected, in UTC",
  resolved_at: "When the case was closed, in UTC",
  location: "Where the vehicle was",
  event_id: "Unique identifier for the event",
  event_type: "What happened to the vehicle",
  event_time: "When it happened, in UTC",
  battery_pct: "Battery charge of the vehicle",
  state: "Whether the vehicle can be rented",
  last_event_time: "When the vehicle last reported, in UTC",
  zone_id: "Unique identifier for the zone",
  name: "Display name",
  zone_type: "What the zone is for",
  max_vehicles: "How many vehicles the bay holds",
  speed_limit_kmh: "Speed limit inside the zone",
  geometry: "Outline of the area",
  district_id: "Unique identifier for the neighbourhood",
  area_type: "The character of the area",
  population: "Number of residents",
  rule_id: "Unique identifier for the rule",
  area: "Where the rule applies",
  rule: "Short statement of the rule",
  applies_to: "Which operators the rule applies to",
  vehicle_cap: "Most vehicles an operator may leave in the area",
  valid_from: "Start of validity",
  valid_to: "End of validity",
};

type Section = "data" | "zones" | "regulations";


type Column = {
  name: string;
  description: string;
  type: ColumnType;
  unit: string;
  /** Category columns only: the distinct values, in display order. */
  values?: string[];
  /** Keyed by value. A value with no entry falls back to the palette. */
  styles?: Record<string, CategoryStyle>;
  /** Category columns only: a map shows logos from this zoom, colour dots below it. */
  logoZoom?: number;
};

type Dataset = {
  id: string;
  /** Where this dataset's category styles are saved. Defaults to `id`. */
  storageKey?: string;
  section: Section;
  title: string;
  description: string;
  aiGenerated?: boolean;
  /** Platform-provided stream rather than something the team uploaded. */
  vip?: boolean;
  /** Regulations only. */
  status?: "active" | "inactive";
  rowRepresents?: string;
  owner: string;
  domain: string;
  uploadedAt: string;
  dateRange?: [string, string];
  rows: number;
  columns: Column[];
  /** Real rows, when the dataset came from a file. Otherwise a preview is generated. */
  preview?: string[][];
  /**
   * Where each row is, when the file has a geometry column, tagged with the
   * value of `mapColumn`. Kept apart from `preview` because the table needs
   * only a page of rows and a map of 2,000 trips needs all of them.
   */
  mapPoints?: CategoryPoint[];
  /** Areas, for a file whose geometry is polygons: drawn as shapes, not points. */
  mapShapes?: CategoryShape[];
  /** The category column the map colours by. */
  mapColumn?: string;
  seed: number;
};

const COLUMN_TYPES: ColumnType[] = [
  "id",
  "category",
  "geometry",
  "timestamp",
  "number",
  "text",
];

const TYPE_ICON: Record<ColumnType, React.ComponentType<{ className?: string }>> = {
  id: Hash,
  category: Tag,
  geometry: MapPin,
  timestamp: Calendar,
  number: Hash,
  text: Type,
};

/* -------------------------------------------------------------------------- */
/* Helpers                                                                     */
/* -------------------------------------------------------------------------- */

const SECTIONS: {
  id: Section;
  label: string;
  icon: React.ComponentType<{ className?: string }>;
}[] = [
  { id: "data", label: "Data", icon: Database },
  { id: "zones", label: "Zones", icon: Shapes },
  { id: "regulations", label: "Regulations", icon: Scale },
];

/** Fixed locale and zone: the page is statically exported, so a server and a
 *  browser in different zones would otherwise render different dates. */
const dateFormat = new Intl.DateTimeFormat("en", {
  dateStyle: "medium",
  timeZone: "UTC",
});
const dateTimeFormat = new Intl.DateTimeFormat("en", {
  dateStyle: "medium",
  timeStyle: "short",
  timeZone: "UTC",
});
const count = new Intl.NumberFormat("en");

/** Small deterministic PRNG, so a dataset's preview is the same every render. */
function rng(seed: number) {
  let s = seed >>> 0 || 1;
  return () => {
    s = (s * 1664525 + 1013904223) >>> 0;
    return s / 2 ** 32;
  };
}

function previewRows(dataset: Dataset, n = 40): string[][] {
  if (dataset.preview) return dataset.preview;
  const next = rng(dataset.seed * 97);
  return Array.from({ length: n }, (_, r) =>
    dataset.columns.map((c) => {
      switch (c.type) {
        case "id":
          return String(4302774000 + Math.floor(next() * 12000));
        case "category":
          return c.values?.[Math.floor(next() * c.values.length)] ?? "";
        case "timestamp": {
          const t = Date.UTC(2025, 3, 1 + Math.floor(next() * 28), 7 + Math.floor(next() * 12), Math.floor(next() * 60));
          return dateTimeFormat.format(t);
        }
        case "number":
          return (next() * 100).toFixed(1);
        case "geometry":
          return `LINESTRING (${(0.1 + next() * 0.05).toFixed(4)} ${(49.48 + next() * 0.03).toFixed(4)}, …)`;
        default:
          return `${c.name.toLowerCase()}_${r + 1}`;
      }
    }),
  );
}

function styleFor(column: Column, value: string): CategoryStyle {
  const values = column.values ?? [];
  return (
    resolveStyles(values, { values: column.styles })[value] ?? {
      color: CATEGORY_PALETTE[0],
    }
  );
}

/** A stylised street grid, standing in for the map thumbnail the platform renders. */
function Thumbnail({ seed, className }: { seed: number; className?: string }) {
  const next = rng(seed);
  // Streets run roughly east-west and north-south with a little wobble, the way
  // a city grid reads from far away. One of them is the dataset's own route.
  const streets = [
    ...Array.from({ length: 4 }, (_, i) => {
      const y = 8 + i * 15 + (next() - 0.5) * 6;
      return `M-2 ${y.toFixed(1)} Q50 ${(y + (next() - 0.5) * 10).toFixed(1)} 102 ${(y + (next() - 0.5) * 8).toFixed(1)}`;
    }),
    ...Array.from({ length: 6 }, (_, i) => {
      const x = 8 + i * 17 + (next() - 0.5) * 6;
      return `M${x.toFixed(1)} -2 Q${(x + (next() - 0.5) * 10).toFixed(1)} 30 ${(x + (next() - 0.5) * 8).toFixed(1)} 62`;
    }),
  ];
  const route = `M${(next() * 20).toFixed(1)} ${(10 + next() * 40).toFixed(1)} C30 ${(next() * 60).toFixed(1)} 60 ${(next() * 60).toFixed(1)} ${(80 + next() * 20).toFixed(1)} ${(10 + next() * 40).toFixed(1)}`;
  return (
    <div className={cn("bg-muted relative overflow-hidden", className)} aria-hidden>
      <svg viewBox="0 0 100 60" preserveAspectRatio="xMidYMid slice" className="absolute inset-0 size-full">
        {streets.map((d, i) => (
          <path key={i} d={d} fill="none" className="stroke-border" strokeWidth="1.1" />
        ))}
        <path d={route} fill="none" className="stroke-primary" strokeWidth="1.6" strokeLinecap="round" />
      </svg>
    </div>
  );
}


/**
 * The dataset's own geometry, drawn small: points and areas in their category
 * colours on the card's background. What a card shows until its map has been
 * opened and photographed -- it needs no WebGL and no tiles, so a list of a
 * dozen of them costs nothing, and it is the data rather than a stand-in.
 */
function DataPlot({ dataset, className }: { dataset: Dataset; className?: string }) {
  const column = dataset.columns.find((c) => c.name === dataset.mapColumn);
  const styles = resolveStyles(column?.values ?? [""], { values: column?.styles });
  const colour = (category: string) => styles[category]?.color ?? CATEGORY_PALETTE[0];

  const points = dataset.mapPoints ?? [];
  const shapes = dataset.mapShapes ?? [];
  let [w, s, e, n] = [Infinity, Infinity, -Infinity, -Infinity];
  for (const { position: [x, y] } of points) [w, s, e, n] = [Math.min(w, x), Math.min(s, y), Math.max(e, x), Math.max(n, y)];
  for (const { ring } of shapes) for (const [x, y] of ring) [w, s, e, n] = [Math.min(w, x), Math.min(s, y), Math.max(e, x), Math.max(n, y)];

  // The frame is the card's picture, about 3.7 times wider than tall. Longitude
  // degrees are shorter than latitude ones away from the equator, so the shape
  // is squared up before it is fitted into it.
  const k = Math.cos(((s + n) / 2) * (Math.PI / 180));
  const spanX = Math.max((e - w) * k, 1e-6);
  const spanY = Math.max(n - s, 1e-6);
  const scale = Math.min(94 / spanX, 24 / spanY);
  const ox = (100 - spanX * scale) / 2;
  const oy = (27 - spanY * scale) / 2;
  const px = (x: number) => ox + (x - w) * k * scale;
  const py = (y: number) => oy + (n - y) * scale;

  // A thousand dots add nothing a few hundred do not already say.
  const stride = Math.max(1, Math.ceil(points.length / 400));

  return (
    <div className={cn("bg-muted relative overflow-hidden", className)} aria-hidden>
      <svg viewBox="0 0 100 27" preserveAspectRatio="xMidYMid slice" className="absolute inset-0 size-full">
        {shapes.map((shape, i) => (
          <polygon
            key={i}
            points={shape.ring.map(([x, y]) => `${px(x).toFixed(1)},${py(y).toFixed(1)}`).join(" ")}
            fill={colour(shape.category)}
            fillOpacity={0.4}
            stroke={colour(shape.category)}
            strokeWidth={0.3}
          />
        ))}
        {points.filter((_, i) => i % stride === 0).map((p, i) => (
          <circle key={i} cx={px(p.position[0])} cy={py(p.position[1])} r={0.7} fill={colour(p.category)} fillOpacity={0.9} />
        ))}
      </svg>
    </div>
  );
}

/* -------------------------------------------------------------------------- */
/* Map thumbnails                                                              */
/* -------------------------------------------------------------------------- */

type Scheme = "light" | "dark";
/** v2: one picture per theme. v1 held a single picture of whichever theme was showing. */
const THUMB_KEY = "vianova:dataset-thumb:v2:";
const THUMB_WIDTH = 360;
/** A card's picture is a wide, short strip; the map is taller, so its middle is kept. */
const THUMB_HEIGHT = 120;

/** The last picture of this dataset's map in a theme, as a data URL, if there is one. */
function readThumb(dataset: Dataset, scheme: Scheme): string | null {
  try {
    return window.localStorage.getItem(`${THUMB_KEY}${scheme}:${storageKeyOf(dataset)}`);
  } catch {
    return null;
  }
}

function writeThumb(dataset: Dataset, scheme: Scheme, url: string) {
  try {
    window.localStorage.setItem(`${THUMB_KEY}${scheme}:${storageKeyOf(dataset)}`, url);
  } catch {
    /* storage is full or blocked: the card keeps its drawn stand-in */
  }
}

/**
 * Keeps the dataset's card thumbnail up to date with what its map shows.
 *
 * Whenever the map has settled after the reader moved it, or changed a colour
 * or logo, it takes a small picture of itself, filed under the theme it is
 * drawn in. The list then shows the map as it was last seen, not a drawing of
 * one. The detail page runs a second, hidden map in the other theme to take
 * that theme's picture, so the list has one for each.
 *
 * A WebGL canvas can only be read in the same task that drew it, so the picture
 * is taken from inside a render forced for the purpose rather than at an idle
 * moment, when the buffer has already been cleared.
 */
function useMapThumbnail(
  map: MapLibreMap | null,
  dataset: Dataset,
  scheme: Scheme | null,
  layerId: string,
  stale: unknown,
) {
  const datasetRef = React.useRef(dataset);
  datasetRef.current = dataset;
  const schemeRef = React.useRef(scheme);
  schemeRef.current = scheme;
  const dirty = React.useRef(true);
  // A map told to change theme swaps its style a moment later. Until the new
  // style has loaded it is still painting the old theme, and a picture taken
  // then would be filed under the wrong one.
  const awaitingStyle = React.useRef(false);
  const lastScheme = React.useRef(scheme);

  // A change of colours, logos or points means the picture is out of date.
  React.useEffect(() => {
    dirty.current = true;
  }, [stale]);

  React.useEffect(() => {
    if (lastScheme.current === scheme) return;
    // null to a theme is the page finding out which one it is, not a change:
    // the map was created in it, and no style swap is coming.
    const changed = lastScheme.current !== null;
    lastScheme.current = scheme;
    if (!changed) return;
    awaitingStyle.current = true;
    dirty.current = true;
  }, [scheme]);

  React.useEffect(() => {
    if (!map) return;
    const markDirty = () => {
      dirty.current = true;
    };
    const onStyle = () => {
      awaitingStyle.current = false;
      dirty.current = true;
    };
    const onIdle = () => {
      // Idle can arrive before the layer has been built; wait for the next one.
      if (!dirty.current || awaitingStyle.current || !schemeRef.current || !map.getLayer(layerId)) return;
      dirty.current = false;
      map.once("render", () => {
        try {
          const source = map.getCanvas();
          if (!source.width || !source.height) return;
          const out = document.createElement("canvas");
          out.width = THUMB_WIDTH;
          out.height = THUMB_HEIGHT;
          const keep = Math.min(source.height, (source.width * THUMB_HEIGHT) / THUMB_WIDTH);
          out
            .getContext("2d")
            ?.drawImage(
              source,
              0,
              (source.height - keep) / 2,
              source.width,
              keep,
              0,
              0,
              THUMB_WIDTH,
              THUMB_HEIGHT,
            );
          writeThumb(datasetRef.current, schemeRef.current!, out.toDataURL("image/jpeg", 0.72));
        } catch {
          /* a canvas the browser will not let us read */
        }
      });
      map.triggerRepaint();
    };
    map.on("moveend", markDirty);
    map.on("style.load", onStyle);
    map.on("idle", onIdle);
    return () => {
      map.off("moveend", markDirty);
      map.off("style.load", onStyle);
      map.off("idle", onIdle);
    };
  }, [map, layerId]);
}

/* -------------------------------------------------------------------------- */
/* Dataset card                                                                */
/* -------------------------------------------------------------------------- */

/**
 * What a dataset looks like, at whatever size its card or row gives it: the last
 * photograph of its map if there is one, else its own geometry drawn small, else
 * a street-grid stand-in. A stream with no rows has nothing to draw, which is
 * the one case the platform shows its broken-image placeholder for.
 */
function DatasetPicture({ dataset, className }: { dataset: Dataset; className?: string }) {
  // Read after mount: the server has no localStorage, so reading it while
  // hydrating would put the two out of step.
  const scheme = useColorScheme();
  const [thumb, setThumb] = React.useState<string | null>(null);
  React.useEffect(() => setThumb(scheme ? readThumb(dataset, scheme) : null), [dataset, scheme]);

  if (dataset.rows === 0)
    return (
      <div className={cn("bg-muted text-muted-foreground flex items-center justify-center", className)}>
        <ImageOff className="size-5" aria-hidden />
        <span className="sr-only">No preview available</span>
      </div>
    );
  if (thumb)
    return (
      // eslint-disable-next-line @next/next/no-img-element
      <img src={thumb} alt="" className={cn("bg-muted w-full object-cover", className)} />
    );
  if (dataset.mapPoints || dataset.mapShapes) return <DataPlot dataset={dataset} className={className} />;
  return <Thumbnail seed={dataset.seed} className={className} />;
}

function DatasetCard({
  dataset,
  onOpen,
}: {
  dataset: Dataset;
  onOpen: () => void;
}) {
  return (
    <button
      type="button"
      onClick={onOpen}
      className="group bg-card text-card-foreground focus-visible:ring-ring flex w-full min-w-0 flex-col overflow-hidden rounded-xl border text-left transition-colors hover:border-foreground/25 focus-visible:ring-2 focus-visible:outline-none"
    >
      <div className="relative">
        <DatasetPicture dataset={dataset} className="h-24" />
        {dataset.vip ? (
          <Badge variant="secondary" className="absolute top-2 left-2">
            VIP
          </Badge>
        ) : null}
      </div>
      <div className="flex min-w-0 flex-1 flex-col gap-1.5 p-3">
        <h3 className="truncate text-sm font-medium">{dataset.title}</h3>
        {dataset.description ? (
          <p className="text-muted-foreground line-clamp-2 text-xs">
            {dataset.description}
          </p>
        ) : null}
        {dataset.aiGenerated ? (
          <Badge variant="outline" className="mt-0.5">
            <Sparkles data-icon="inline-start" />
            AI-generated
          </Badge>
        ) : null}
        {dataset.status ? (
          <Badge
            variant={dataset.status === "active" ? "default" : "secondary"}
            className="mt-0.5 capitalize"
          >
            {dataset.status}
          </Badge>
        ) : null}
        <p className="text-muted-foreground mt-auto pt-2 text-xs">
          {dateTimeFormat.format(new Date(dataset.uploadedAt))}
        </p>
      </div>
    </button>
  );
}

/** The same dataset as one line: a small picture, its name and what it is, and when it was added. */
function DatasetRow({ dataset, onOpen }: { dataset: Dataset; onOpen: () => void }) {
  return (
    <button
      type="button"
      onClick={onOpen}
      className="group bg-card text-card-foreground focus-visible:ring-ring flex w-full min-w-0 items-center gap-3 rounded-xl border p-2 text-left transition-colors hover:border-foreground/25 focus-visible:ring-2 focus-visible:outline-none"
    >
      <DatasetPicture dataset={dataset} className="h-12 w-20 shrink-0 rounded-md" />
      <div className="min-w-0 flex-1">
        <h3 className="truncate text-sm font-medium">{dataset.title}</h3>
        {dataset.description ? (
          <p className="text-muted-foreground truncate text-xs">{dataset.description}</p>
        ) : null}
      </div>
      <div className="flex shrink-0 items-center gap-2">
        {dataset.vip ? <Badge variant="secondary">VIP</Badge> : null}
        {dataset.aiGenerated ? (
          <Badge variant="outline" className="hidden sm:inline-flex">
            <Sparkles data-icon="inline-start" />
            AI-generated
          </Badge>
        ) : null}
        {dataset.status ? (
          <Badge variant={dataset.status === "active" ? "default" : "secondary"} className="capitalize">
            {dataset.status}
          </Badge>
        ) : null}
        <span className="text-muted-foreground hidden pr-2 text-xs whitespace-nowrap md:inline">
          {dateTimeFormat.format(new Date(dataset.uploadedAt))}
        </span>
      </div>
    </button>
  );
}

function RowSkeleton() {
  return (
    <div className="bg-card flex items-center gap-3 rounded-xl border p-2" aria-hidden>
      <Skeleton className="h-12 w-20 shrink-0 rounded-md" />
      <div className="flex-1 space-y-2">
        <Skeleton className="h-4 w-1/3" />
        <Skeleton className="h-3 w-2/3" />
      </div>
    </div>
  );
}

function CardSkeleton() {
  return (
    <div className="bg-card overflow-hidden rounded-xl border" aria-hidden>
      <Skeleton className="h-24 rounded-none" />
      <div className="space-y-2 p-3">
        <Skeleton className="h-4 w-3/4" />
        <Skeleton className="h-3 w-full" />
        <Skeleton className="h-3 w-1/3" />
      </div>
    </div>
  );
}

/* -------------------------------------------------------------------------- */
/* Category picker                                                             */
/* -------------------------------------------------------------------------- */

/** Ready-made badges: the two a logo most often needs, so it is one click away. */
const BADGE_CHOICES = [
  { label: "White", hex: "#ffffff" },
  { label: "Dark", hex: "#111827" },
] as const;

/**
 * One category value's colour and logo, and how they will look on a map.
 *
 * The colour is the dot a map draws zoomed out. The badge -- the logo on a disc
 * -- is what it draws zoomed in, and its disc is the same colour unless it is
 * given its own, because what makes a dot easy to tell apart and what makes a
 * logo easy to read are often different colours. The picker shows both, and
 * says so when a logo will not read on its badge.
 */
function CategoryStylePicker({
  value,
  style,
  logoZoom,
  onChange,
}: {
  value: string;
  style: CategoryStyle;
  logoZoom: number;
  onChange: (next: CategoryStyle) => void;
}) {
  const fileRef = React.useRef<HTMLInputElement>(null);
  const [busy, setBusy] = React.useState(false);
  const [error, setError] = React.useState<string | null>(null);
  const advice = adviseLogo(style);

  const upload = async (file: File | undefined) => {
    if (!file) return;
    setBusy(true);
    setError(null);
    try {
      const { logoColor, ...logo } = await prepareLogo(file);
      // The dot takes the logo's own colour, so the dot and the logo that
      // replaces it read as the same thing. The badge is cleared first, then
      // given a white or dark disc if the logo would be lost on its own colour,
      // which is the usual case: a logo in its own colour on a disc of that colour.
      const next: CategoryStyle = {
        ...style,
        ...logo,
        badge: undefined,
        color: logoColor ?? style.color,
      };
      const fix = adviseLogo(next).find((a) => a.kind === "warning")?.suggestion;
      onChange(fix ? { ...next, badge: fix } : next);
    } catch (e) {
      setError(e instanceof Error ? e.message : "That file could not be used.");
    } finally {
      setBusy(false);
    }
  };

  return (
    <Popover>
      <PopoverTrigger
        render={
          <Button
            variant="ghost"
            size="icon-sm"
            aria-label={`Colour and logo for ${value}`}
          />
        }
      >
        <CategoryBadge color={badgeColor(style)} logo={style.logo} logoKind={style.logoKind} size={22} />
      </PopoverTrigger>
      <PopoverContent align="start" className="w-80 space-y-4">
        <div className="space-y-1.5">
          <p className="text-xs font-medium">On the map</p>
          <div className="bg-muted/50 flex items-center justify-around rounded-lg border p-3">
            <div className="flex flex-col items-center gap-1.5">
              <span
                aria-hidden
                className="size-3.5 rounded-full border border-white"
                style={{ backgroundColor: style.color }}
              />
              <span className="text-muted-foreground text-[11px]">Below zoom {logoZoom}</span>
            </div>
            <div className="flex flex-col items-center gap-1.5">
              <CategoryBadge color={badgeColor(style)} logo={style.logo} logoKind={style.logoKind} size={44} />
              <span className="text-muted-foreground text-[11px]">From zoom {logoZoom}</span>
            </div>
          </div>
        </div>

        <div className="space-y-1.5">
          <p className="text-xs font-medium">Colour</p>
          <div className="flex flex-wrap items-center gap-1.5">
            {CATEGORY_PALETTE.map((swatch) => (
              <button
                key={swatch}
                type="button"
                aria-label={`Use ${swatch}`}
                aria-pressed={style.color === swatch}
                onClick={() => onChange({ ...style, color: swatch })}
                className="focus-visible:ring-ring size-6 rounded-full border focus-visible:ring-2 focus-visible:outline-none aria-pressed:ring-2 aria-pressed:ring-offset-1 aria-pressed:ring-offset-background aria-pressed:ring-foreground"
                style={{ backgroundColor: swatch }}
              />
            ))}
            <label className="text-muted-foreground hover:text-foreground focus-within:ring-ring flex size-6 cursor-pointer items-center justify-center rounded-full border border-dashed text-[10px] focus-within:ring-2">
              <span aria-hidden>+</span>
              <span className="sr-only">Custom colour</span>
              <input
                type="color"
                className="sr-only"
                value={/^#[0-9a-f]{6}$/i.test(style.color) ? style.color : "#0f766e"}
                onChange={(e) => onChange({ ...style, color: e.target.value })}
              />
            </label>
          </div>
        </div>

        {style.logo ? (
          <div className="space-y-1.5">
            <p className="text-xs font-medium">Badge</p>
            <div className="flex flex-wrap items-center gap-1.5">
              <button
                type="button"
                aria-pressed={style.badge === undefined}
                onClick={() => onChange({ ...style, badge: undefined })}
                className="focus-visible:ring-ring hover:bg-muted text-muted-foreground aria-pressed:text-foreground aria-pressed:border-foreground h-6 rounded-full border px-2 text-[11px] focus-visible:ring-2 focus-visible:outline-none"
              >
                Same as dot
              </button>
              {BADGE_CHOICES.map(({ label, hex }) => (
                <button
                  key={hex}
                  type="button"
                  aria-label={`${label} badge`}
                  aria-pressed={style.badge === hex}
                  onClick={() => onChange({ ...style, badge: hex })}
                  className="focus-visible:ring-ring size-6 rounded-full border focus-visible:ring-2 focus-visible:outline-none aria-pressed:ring-2 aria-pressed:ring-offset-1 aria-pressed:ring-offset-background aria-pressed:ring-foreground"
                  style={{ backgroundColor: hex }}
                />
              ))}
              <label className="text-muted-foreground hover:text-foreground focus-within:ring-ring flex size-6 cursor-pointer items-center justify-center rounded-full border border-dashed text-[10px] focus-within:ring-2">
                <span aria-hidden>+</span>
                <span className="sr-only">Custom badge colour</span>
                <input
                  type="color"
                  className="sr-only"
                  value={/^#[0-9a-f]{6}$/i.test(badgeColor(style)) ? badgeColor(style) : "#ffffff"}
                  onChange={(e) => onChange({ ...style, badge: e.target.value })}
                />
              </label>
            </div>
            <p className="text-muted-foreground text-[11px]">
              What the logo sits on. The dot keeps its own colour.
            </p>
          </div>
        ) : null}

        <div className="space-y-1.5">
          <p className="text-xs font-medium">Logo</p>
          <div className="flex items-center gap-2">
            <Button variant="outline" size="sm" disabled={busy} onClick={() => fileRef.current?.click()}>
              <ImagePlus data-icon="inline-start" />
              {busy ? "Reading…" : style.logo ? "Replace" : "Upload"}
            </Button>
            {style.logo ? (
              <Button
                variant="ghost"
                size="sm"
                onClick={() => onChange({ color: style.color })}
              >
                <X data-icon="inline-start" />
                Remove
              </Button>
            ) : null}
            <input
              ref={fileRef}
              type="file"
              accept="image/*"
              className="sr-only"
              tabIndex={-1}
              aria-label={`Logo file for ${value}`}
              onChange={(e) => {
                void upload(e.target.files?.[0]);
                e.target.value = "";
              }}
            />
          </div>
          {error ? (
            <p role="alert" className="text-destructive text-xs">
              {error}
            </p>
          ) : null}
          {advice.map((a) => (
            <div
              key={a.message}
              className={cn(
                "flex items-start gap-2 rounded-md border p-2 text-xs",
                a.kind === "warning"
                  ? "border-destructive/40 text-destructive"
                  : "text-muted-foreground",
              )}
            >
              {a.kind === "warning" ? <TriangleAlert className="mt-0.5 size-3.5 shrink-0" /> : null}
              <div className="space-y-1.5">
                <p>{a.message}</p>
                {a.suggestion ? (
                  <Button
                    variant="outline"
                    size="xs"
                    onClick={() => onChange({ ...style, badge: a.suggestion! })}
                  >
                    Use {a.suggestion === "#ffffff" ? "a white" : "a dark"} badge
                  </Button>
                ) : null}
              </div>
            </div>
          ))}
        </div>
      </PopoverContent>
    </Popover>
  );
}

/* -------------------------------------------------------------------------- */
/* Detail                                                                      */
/* -------------------------------------------------------------------------- */

function ColumnRow({
  column,
  onChange,
}: {
  column: Column;
  onChange: (next: Column) => void;
}) {
  const [open, setOpen] = React.useState(false);
  const Icon = TYPE_ICON[column.type];
  const expandable = column.type === "category" && !!column.values?.length;
  const logoZoom = column.logoZoom ?? DEFAULT_LOGO_ZOOM;

  return (
    <>
      <TableRow>
        <TableCell className="font-medium">
          <div className="flex items-center gap-1.5">
            {expandable ? (
              <button
                type="button"
                aria-expanded={open}
                aria-label={`${open ? "Hide" : "Show"} values of ${column.name}`}
                onClick={() => setOpen((o) => !o)}
                className="hover:bg-muted focus-visible:ring-ring -ml-1 rounded p-0.5 focus-visible:ring-2 focus-visible:outline-none"
              >
                <ChevronRight
                  className={cn("size-3.5 transition-transform", open && "rotate-90")}
                />
              </button>
            ) : (
              <span className="w-3.5" aria-hidden />
            )}
            <Icon className="text-muted-foreground size-3.5 shrink-0" />
            <span className="truncate">{column.name}</span>
          </div>
        </TableCell>
        <TableCell className="max-w-44">
          <InlineEdit
            value={column.description}
            label={`description of ${column.name}`}
            placeholder="Add a description"
            onValueChange={(description) => onChange({ ...column, description })}
            className="max-w-full"
          />
        </TableCell>
        <TableCell>
          <Select
            value={column.type}
            onValueChange={(type) =>
              onChange({ ...column, type: (type ?? column.type) as ColumnType })
            }
          >
            <SelectTrigger size="sm" className="w-32" aria-label={`Type of ${column.name}`}>
              <SelectValue />
            </SelectTrigger>
            <SelectContent>
              {COLUMN_TYPES.map((t) => (
                <SelectItem key={t} value={t}>
                  {t}
                </SelectItem>
              ))}
            </SelectContent>
          </Select>
        </TableCell>
        <TableCell className="text-muted-foreground">
          <InlineEdit
            value={column.unit === "N/A" ? "" : column.unit}
            label={`unit of ${column.name}`}
            placeholder="N/A"
            onValueChange={(unit) => onChange({ ...column, unit: unit || "N/A" })}
          />
        </TableCell>
      </TableRow>
      {open && expandable ? (
        <>
          {column.values!.map((value) => (
            <TableRow key={value} className="bg-muted/30">
              <TableCell colSpan={4} className="py-1 pl-10">
                <div className="flex items-center gap-2">
                  <CategoryStylePicker
                    value={value}
                    style={styleFor(column, value)}
                    logoZoom={logoZoom}
                    onChange={(next) =>
                      onChange({
                        ...column,
                        // Written out in full, not just the value that changed:
                        // a value left on its palette default would otherwise
                        // drift if the palette order ever did.
                        styles: { ...resolveStyles(column.values!, { values: column.styles }), [value]: next },
                      })
                    }
                  />
                  <span className="text-sm">{value}</span>
                </div>
              </TableCell>
            </TableRow>
          ))}
        </>
      ) : null}
    </>
  );
}

function PreviewTable({ dataset }: { dataset: Dataset }) {
  const rows = React.useMemo(() => previewRows(dataset), [dataset]);
  const [sort, setSort] = React.useState<{ index: number; dir: "asc" | "desc" } | null>(null);

  const sorted = React.useMemo(() => {
    if (!sort) return rows;
    const sortType = dataset.columns[sort.index]?.type;
    const numeric = sortType === "number" || sortType === "id";
    return [...rows].sort((a, b) => {
      const x = a[sort.index] ?? "";
      const y = b[sort.index] ?? "";
      const cmp = numeric ? Number(x) - Number(y) : x.localeCompare(y);
      return sort.dir === "asc" ? cmp : -cmp;
    });
  }, [rows, sort, dataset.columns]);

  return (
    <Table>
      <TableHeader>
        <TableRow>
          {dataset.columns.map((c, i) => {
            const Icon = TYPE_ICON[c.type];
            const active = sort?.index === i;
            const SortIcon = !active ? ArrowUpDown : sort.dir === "asc" ? ArrowUp : ArrowDown;
            return (
              <TableHead
                key={c.name}
                aria-sort={active ? (sort.dir === "asc" ? "ascending" : "descending") : "none"}
              >
                <button
                  type="button"
                  onClick={() =>
                    setSort(
                      active && sort.dir === "desc"
                        ? null
                        : { index: i, dir: active ? "desc" : "asc" },
                    )
                  }
                  className="hover:text-foreground focus-visible:ring-ring -mx-1 inline-flex items-center gap-1.5 rounded px-1 whitespace-nowrap focus-visible:ring-2 focus-visible:outline-none"
                >
                  <Icon className="size-3.5" />
                  {c.name}
                  <SortIcon className={cn("size-3", !active && "opacity-40")} />
                </button>
              </TableHead>
            );
          })}
        </TableRow>
      </TableHeader>
      <TableBody>
        {sorted.map((row, r) => (
          <TableRow key={r}>
            {row.map((cell, c) => (
              <TableCell key={c} className="max-w-48 truncate whitespace-nowrap tabular-nums">
                {cell}
              </TableCell>
            ))}
          </TableRow>
        ))}
      </TableBody>
    </Table>
  );
}

function Fact({
  label,
  children,
}: {
  label: string;
  children: React.ReactNode;
}) {
  return (
    <div className="min-w-0 space-y-1">
      <dt className="text-muted-foreground text-xs">{label}</dt>
      <dd className="flex items-center gap-1.5 text-sm">{children}</dd>
    </div>
  );
}

function DatasetDetail({
  dataset,
  saveFailed,
  onBack,
  onChange,
  onDelete,
}: {
  dataset: Dataset;
  /** The last change to a category's colour or logo could not be saved. */
  saveFailed: boolean;
  onBack: () => void;
  onChange: (next: Dataset) => void;
  onDelete: () => void;
}) {
  const [tab, setTab] = React.useState<"columns" | "preview">("columns");
  // Edited in place and committed on blur, like the inline fields beside it.
  const [draft, setDraft] = React.useState(dataset.description);
  React.useEffect(() => setDraft(dataset.description), [dataset.description]);

  return (
    <div className="mx-auto w-full max-w-6xl space-y-4 p-4 md:p-6">
      <div className="flex items-center gap-3">
        <Button variant="outline" size="icon-sm" onClick={onBack} aria-label="Back to data">
          <ArrowLeft />
        </Button>
        <h2 className="truncate text-lg font-semibold tracking-tight">{dataset.title}</h2>
      </div>

      {saveFailed ? (
        <Alert variant="destructive">
          <TriangleAlert />
          <AlertTitle>Couldn&apos;t save your logos</AlertTitle>
          <AlertDescription>
            This browser&apos;s storage is full or blocked, so the map won&apos;t see these changes
            and they will be lost on reload.
          </AlertDescription>
        </Alert>
      ) : null}

      <div className="grid gap-4 lg:grid-cols-[minmax(0,4fr)_minmax(0,8fr)]">
        <div className="min-w-0 space-y-4">
        <DatasetMap dataset={dataset} />
        <section className="bg-card h-fit rounded-xl border">
          <h3 className="border-b px-4 py-3 text-sm font-medium">Data information</h3>
          <div className="space-y-4 p-4">
            <div className="space-y-1.5">
              <label htmlFor={`${dataset.id}-description`} className="text-muted-foreground flex items-center gap-1 text-xs">
                Description
                {dataset.aiGenerated ? <Sparkles className="size-3" aria-label="AI-generated" /> : null}
              </label>
              <Textarea
                id={`${dataset.id}-description`}
                value={draft}
                placeholder="Describe what this data contains"
                rows={3}
                onChange={(e) => setDraft(e.target.value)}
                onBlur={() => draft !== dataset.description && onChange({ ...dataset, description: draft })}
              />
            </div>
            {dataset.rowRepresents ? (
              <p className="text-muted-foreground text-xs">
                Each row represents:{" "}
                <span className="text-foreground">{dataset.rowRepresents}</span>
              </p>
            ) : null}
            <dl className="grid grid-cols-2 gap-4">
              <Fact label="Owner">
                <Avatar className="size-5">
                  <AvatarFallback className="text-[10px]">
                    {dataset.owner.split(" ").map((p) => p[0]).join("")}
                  </AvatarFallback>
                </Avatar>
                <span className="truncate">{dataset.owner}</span>
              </Fact>
              <Fact label="Uploaded at">{dateFormat.format(new Date(dataset.uploadedAt))}</Fact>
              <Fact label="Domain">
                <Badge variant="secondary">{dataset.domain}</Badge>
              </Fact>
              <Fact label="Date range">
                {dataset.dateRange
                  ? `${dateFormat.format(new Date(dataset.dateRange[0]))} – ${dateFormat.format(new Date(dataset.dateRange[1]))}`
                  : "—"}
              </Fact>
              <Fact label="Records">
                {count.format(dataset.rows)} {dataset.rows === 1 ? "row" : "rows"} / {dataset.columns.length}{" "}
                {dataset.columns.length === 1 ? "column" : "columns"}
              </Fact>
            </dl>
            <ConfirmDialog
              trigger={
                <Button variant="destructive" size="sm">
                  <Trash2 data-icon="inline-start" />
                  Delete data
                </Button>
              }
              title={`Delete ${dataset.title}?`}
              description="This removes the dataset and everything built on it. It cannot be undone."
              confirmLabel="Delete"
              destructive
              onConfirm={onDelete}
            />
          </div>
        </section>
        </div>

        <section className="bg-card min-w-0 rounded-xl border">
          <div className="flex items-center justify-between gap-2 border-b px-4 py-3">
            <h3 className="text-sm font-medium">Metadata preview</h3>
          </div>
          <div className="space-y-3 p-4">
            <Tabs value={tab} onValueChange={(v) => setTab(v as typeof tab)}>
              <TabsList>
                <TabsTrigger value="columns">
                  <Columns3 />
                  Column description
                </TabsTrigger>
                <TabsTrigger value="preview">
                  <Table2 />
                  Data preview
                </TabsTrigger>
              </TabsList>
            </Tabs>
            {/* A fixed ceiling, so a 40-row preview scrolls inside its panel
                instead of pushing the delete button a screen away. */}
            <div className="max-h-[28rem] overflow-auto">
              {tab === "columns" ? (
                <Table>
                  <TableHeader>
                    <TableRow>
                      <TableHead>Column name</TableHead>
                      <TableHead>Description</TableHead>
                      <TableHead>Type</TableHead>
                      <TableHead>Unit</TableHead>
                    </TableRow>
                  </TableHeader>
                  <TableBody>
                    {dataset.columns.map((c, i) => (
                      <ColumnRow
                        key={c.name}
                        column={c}
                        onChange={(next) =>
                          onChange({
                            ...dataset,
                            columns: dataset.columns.map((x, j) => (j === i ? next : x)),
                          })
                        }
                      />
                    ))}
                  </TableBody>
                </Table>
              ) : (
                <PreviewTable dataset={dataset} />
              )}
            </div>
          </div>
        </section>
      </div>
    </div>
  );
}

/** The first vertex of a WKT geometry: where a trip started, or the point itself. */
const FIRST_VERTEX = /\(\s*(-?\d+(?:\.\d+)?)\s+(-?\d+(?:\.\d+)?)/;
/** Every longitude and latitude pair in a WKT geometry. */
const NUMBER_PAIR = /(-?\d+(?:\.\d+)?)\s+(-?\d+(?:\.\d+)?)/g;
/** A map of this many points is already a blur; more would only cost memory. */
const MAX_MAP_POINTS = 20_000;

/**
 * A small map of the dataset, coloured by its first category column with the
 * same colours and logos the picker sets -- so a change made in the table can
 * be checked here, and what the map workspace will draw is seen before leaving.
 */
function DatasetMap({ dataset }: { dataset: Dataset }) {
  const points = dataset.mapPoints;
  const shapes = dataset.mapShapes;
  const total = (points?.length ?? 0) + (shapes?.length ?? 0);
  const column = dataset.columns.find((c) => c.name === dataset.mapColumn);
  const [map, setMap] = React.useState<MapLibreMap | null>(null);
  // The same map drawn in the other theme, out of sight, so both themes get a
  // thumbnail without the reader having to switch.
  const [ghost, setGhost] = React.useState<MapLibreMap | null>(null);
  const scheme = useColorScheme();
  const otherScheme: Scheme | null = scheme === "dark" ? "light" : scheme === "light" ? "dark" : null;
  const mapBox = React.useRef<HTMLDivElement>(null);
  const [size, setSize] = React.useState<{ width: number; height: number } | null>(null);
  React.useEffect(() => {
    const el = mapBox.current;
    if (!el) return;
    const measure = () => setSize({ width: el.clientWidth, height: el.clientHeight });
    measure();
    const observer = new ResizeObserver(measure);
    observer.observe(el);
    return () => observer.disconnect();
  }, [total]);
  const fitted = React.useRef(false);

  const values = column?.values ?? [];
  const logoZoom = column?.logoZoom ?? DEFAULT_LOGO_ZOOM;
  const styles = React.useMemo(
    // With no category column every point is one value, in the first colour.
    () => resolveStyles(column ? values : [""], { logoZoom, values: column?.styles }),
    // `values` is a new array each render when the column has none.
    // eslint-disable-next-line react-hooks/exhaustive-deps
    [column?.values, column?.styles, logoZoom],
  );

  useCategoryPointLayer({
    map,
    enabled: !!points?.length,
    points: points ?? [],
    styles,
    logoZoom,
    id: "datahub-points",
  });

  useCategoryShapeLayer({
    map,
    enabled: !!shapes?.length,
    shapes: shapes ?? [],
    styles,
    id: "datahub-shapes",
  });
  useCategoryPointLayer({
    map: ghost,
    enabled: !!points?.length,
    points: points ?? [],
    styles,
    logoZoom,
    id: "datahub-points",
  });
  useCategoryShapeLayer({
    map: ghost,
    enabled: !!shapes?.length,
    shapes: shapes ?? [],
    styles,
    id: "datahub-shapes",
  });

  // The hidden map looks wherever the visible one does, at the same size, so
  // the two themes' pictures show the same view.
  React.useEffect(() => {
    if (!map || !ghost) return;
    const follow = () =>
      ghost.jumpTo({
        center: map.getCenter(),
        zoom: map.getZoom(),
        bearing: map.getBearing(),
        pitch: map.getPitch(),
      });
    follow();
    map.on("move", follow);
    return () => {
      map.off("move", follow);
    };
  }, [map, ghost, size]);

  // Frame the data once. Re-framing on every style change would throw away
  // wherever the reader had panned to.
  React.useEffect(() => {
    if (!map || !total || fitted.current) return;
    fitted.current = true;
    let [w, s, e, n] = [Infinity, Infinity, -Infinity, -Infinity];
    const include = (x: number, y: number) => {
      w = Math.min(w, x);
      e = Math.max(e, x);
      s = Math.min(s, y);
      n = Math.max(n, y);
    };
    for (const { position: [x, y] } of points ?? []) include(x, y);
    for (const { ring } of shapes ?? []) for (const [x, y] of ring) include(x, y);
    map.fitBounds([[w, s], [e, n]], { padding: 24, duration: 0, maxZoom: 15 });
  }, [map, points, shapes, total]);

  const thumbLayer = shapes?.length ? "datahub-shapes-fill" : "datahub-points-dots";
  useMapThumbnail(map, dataset, scheme, thumbLayer, styles);
  useMapThumbnail(ghost, dataset, otherScheme, thumbLayer, styles);

  const [logosShown, setLogosShown] = React.useState(false);
  React.useEffect(() => {
    if (!map) return;
    const update = () => setLogosShown(map.getZoom() >= logoZoom);
    update();
    map.on("zoom", update);
    return () => {
      map.off("zoom", update);
    };
  }, [map, logoZoom]);

  return (
    <section className="bg-card min-w-0 overflow-hidden rounded-xl border" data-slot="datahub-map">
      <h3 className="border-b px-4 py-3 text-sm font-medium">Map</h3>
      {total ? (
        <>
          <div ref={mapBox} className="relative h-56 w-full">
            {/* Kept out of sight and out of reach: it only exists to be photographed. */}
            {otherScheme && size ? (
              <div
                aria-hidden
                inert
                className="pointer-events-none fixed top-0 -left-[9999px]"
                style={{ width: size.width, height: size.height }}
              >
                <MapCanvas
                  className="absolute inset-0"
                  workerUrl={WORKER_URL}
                  colorScheme={otherScheme}
                  interactive={false}
                  onStyleReady={setGhost}
                />
              </div>
            ) : null}
            <MapCanvas
              className="absolute inset-0"
              workerUrl={WORKER_URL}
              cooperativeGesturesBelow={1024}
              onStyleReady={setMap}
              fallback={
                <div className="text-muted-foreground flex h-full items-center justify-center p-4 text-center text-xs">
                  The map can&apos;t be shown here because WebGL is unavailable.
                </div>
              }
            />
          </div>
          <div className="space-y-2 p-4">
            <p className="text-muted-foreground text-xs">
              {count.format(total)} {shapes?.length ? (total === 1 ? "area" : "areas") : total === 1 ? "point" : "points"}
              {column ? (
                <>
                  , coloured by <span className="text-foreground">{column.name}</span>
                  {shapes?.length ? "." : ". Zoom in to see logos."}
                </>
              ) : (
                "."
              )}
            </p>
            {column ? (
            <LegendCategorical
              showLogos={logosShown}
              items={values.map((label) => {
                const style = styles[label];
                return {
                  label,
                  color: style?.color ?? "#888888",
                  logo: style?.logo
                    ? {
                        src: style.logo,
                        solid: style.logoKind === "solid",
                        background: badgeColor(style),
                      }
                    : undefined,
                };
              })}
            />
            ) : null}
          </div>
        </>
      ) : (
        <p className="text-muted-foreground p-4 text-xs">
          No map preview: this dataset has no geometry column with readable coordinates.
        </p>
      )}
    </section>
  );
}

/** Past this a browser tab struggles to hold the text, never mind parse it. */
const MAX_UPLOAD_BYTES = 50 * 1024 * 1024;
const PREVIEW_ROWS = 200;
/** A geometry cell can be 100KB of hex; the table only needs to show it exists. */
const CELL_LIMIT = 120;

/**
 * Turns the text of a CSV into a dataset, or says why it cannot.
 *
 * Only the first PREVIEW_ROWS are kept: the dataset's row count comes from the
 * whole file, but holding every row of a multi-million-row export in React
 * state would cost more than the preview is worth.
 */
function datasetFromCsv(id: string, filename: string, text: string): Dataset | string {
  const parsed = parseCsv(text);
  if (parsed.header.length === 0) return "That file is empty.";
  if (parsed.rows.length === 0) return "That file has column names but no rows.";

  const columns: Column[] = inferColumns(parsed).map((c) => ({
    name: c.name,
    type: c.type,
    values: c.values,
    description: "",
    unit: "N/A",
  }));
  // Where to put the dataset on a map: the first geometry column whose cells
  // read as coordinates, coloured by the first category column.
  const header = parsed.header;
  const geometryAt = columns.findIndex((c) => c.type === "geometry");
  // A column with one value tells the map nothing, so the first that varies.
  const categoryAt = (() => {
    const first = columns.findIndex((c) => c.type === "category");
    const varies = columns.findIndex((c) => c.type === "category" && (c.values?.length ?? 0) > 1);
    return varies >= 0 ? varies : first;
  })();
  const mapPoints: CategoryPoint[] = [];
  const mapShapes: CategoryShape[] = [];
  if (geometryAt >= 0) {
    for (const row of parsed.rows) {
      const cell = row[geometryAt] ?? "";
      const category = categoryAt >= 0 ? (row[categoryAt] ?? "") : "";
      if (/^\s*POLYGON/i.test(cell)) {
        const ring = [...cell.matchAll(NUMBER_PAIR)].map((m) => [Number(m[1]), Number(m[2])] as [number, number]);
        if (ring.length >= 4) mapShapes.push({ ring, category });
        continue;
      }
      const m = FIRST_VERTEX.exec(cell);
      if (!m) continue;
      mapPoints.push({ position: [Number(m[1]), Number(m[2])], category });
      if (mapPoints.length >= MAX_MAP_POINTS) break;
    }
  }
  const mapped = mapPoints.length > 0 || mapShapes.length > 0;
  const clip = (v: string) => (v.length > CELL_LIMIT ? `${v.slice(0, CELL_LIMIT)}…` : v);

  return {
    id,
    // The id counts uploads in this session, so it names a different file on
    // the next visit. The filename is what makes the same file find its logos.
    storageKey: `upload:${filename}`,
    section: "data",
    title: filename,
    description: "",
    owner: "You",
    domain: "uploaded",
    uploadedAt: new Date().toISOString(),
    rows: parsed.rows.length,
    columns,
    preview: parsed.rows
      .slice(0, PREVIEW_ROWS)
      .map((row) => parsed.header.map((_, i) => clip(row[i] ?? ""))),
    seed: filename.length,
    mapPoints: mapPoints.length ? mapPoints : undefined,
    mapShapes: mapShapes.length ? mapShapes : undefined,
    mapColumn: categoryAt >= 0 && mapped ? header[categoryAt] : undefined,
  };
}

/* -------------------------------------------------------------------------- */
/* Saved category styles                                                       */
/* -------------------------------------------------------------------------- */

const storageKeyOf = (d: Dataset) => d.storageKey ?? d.id;

/**
 * Puts back whatever styles this browser has saved for a dataset.
 *
 * Done after mount, never in the initial state: the server renders without
 * localStorage, so reading it while hydrating would put the two out of step.
 */
function withSavedStyles(dataset: Dataset): Dataset {
  let changed = false;
  const columns = dataset.columns.map((c) => {
    if (c.type !== "category") return c;
    const saved = readStyleSet(storageKeyOf(dataset), c.name);
    if (!saved) return c;
    changed = true;
    return { ...c, styles: saved.values, logoZoom: saved.logoZoom };
  });
  return changed ? { ...dataset, columns } : dataset;
}

/** False if any column could not be saved, e.g. the browser's storage is full. */
function saveStyles(dataset: Dataset): boolean {
  let ok = true;
  for (const c of dataset.columns) {
    if (c.type !== "category" || (!c.styles && c.logoZoom === undefined)) continue;
    ok =
      writeStyleSet(storageKeyOf(dataset), c.name, {
        logoZoom: c.logoZoom ?? DEFAULT_LOGO_ZOOM,
        values: c.styles ?? {},
      }) && ok;
  }
  return ok;
}

/* -------------------------------------------------------------------------- */
/* Workspace                                                                   */
/* -------------------------------------------------------------------------- */

type ListView = "cards" | "list";
const VIEW_KEY = "vianova:datahub-view:v1";

/**
 * Whether the list shows cards or rows, remembered in this browser.
 *
 * Read after mount, never in the initial state: the server has no localStorage,
 * so reading it while hydrating would put the two out of step.
 */
function useListView() {
  const [view, setView] = React.useState<ListView>("cards");
  React.useEffect(() => {
    try {
      const saved = window.localStorage.getItem(VIEW_KEY);
      if (saved === "cards" || saved === "list") setView(saved);
    } catch {
      /* storage is blocked: the choice lasts until the page is closed */
    }
  }, []);
  const choose = React.useCallback((next: ListView) => {
    setView(next);
    try {
      window.localStorage.setItem(VIEW_KEY, next);
    } catch {
      /* as above */
    }
  }, []);
  return [view, choose] as const;
}

type SortKey = "recent" | "oldest" | "name";
const SORTS: Record<SortKey, string> = {
  recent: "Most recent",
  oldest: "Oldest",
  name: "Name",
};

/**
 * The data hub: browse what the workspace holds, then open a dataset to read
 * and correct its metadata.
 *
 * `status` is how the catalogue itself is doing -- "loading" shows skeletons in
 * place of cards, "error" shows a retry. It is a prop rather than internal
 * state because the host owns the fetch.
 */
export function DatahubWorkspace({
  className,
  datasets: initial = [],
  samples = SAMPLE_FEEDS,
  status: hostStatus = "ready",
  onRetry,
  onUpload,
}: {
  className?: string;
  datasets?: Dataset[];
  /** CSVs to load as sample datasets. Pass null to show only `datasets`. */
  samples?: SampleFeed[] | null;
  status?: "ready" | "loading" | "error";
  onRetry?: () => void;
  /** Called after a file has been read and added, with the dataset it became. */
  onUpload?: (file: File, dataset: Dataset) => void;
}) {
  const [datasets, setDatasets] = React.useState(initial);
  const [saveFailed, setSaveFailed] = React.useState(false);
  const [pending, setPending] = React.useState(samples?.length ?? 0);

  // Styles saved on an earlier visit, or set on the map workspace's other page.
  React.useEffect(() => {
    setDatasets((all) => all.map(withSavedStyles));
  }, []);

  // Each sample is optional: one that cannot be fetched or read is left out,
  // rather than turned into an error about something nobody asked for.
  React.useEffect(() => {
    if (!samples?.length) {
      setPending(0);
      return;
    }
    const controller = new AbortController();
    setPending(samples.length);
    for (const feed of samples) {
      fetch(`${BASE_PATH}/data/${feed.file}`, { signal: controller.signal })
        .then((r) => (r.ok ? r.text() : Promise.reject(new Error(String(r.status)))))
        .then((text) => {
          const parsed = datasetFromCsv(feed.id, feed.file, text);
          if (typeof parsed === "string") return;
          const sample: Dataset = {
            ...parsed,
            // Not the upload key `datasetFromCsv` gave it: the map and reports
            // workspaces look these styles up by this exact id, so it is part
            // of that contract.
            storageKey: feed.id,
            section: feed.section,
            status: feed.status,
            description: feed.description,
            aiGenerated: false,
            rowRepresents: feed.rowRepresents,
            owner: "Vianova",
            domain: feed.domain,
            uploadedAt: feed.uploadedAt,
            dateRange: feed.dateRange,
            columns: parsed.columns.map((c) => ({
              ...c,
              description: SAMPLE_DESCRIPTIONS[c.name] ?? c.description,
              unit: feed.units?.[c.name] ?? c.unit,
            })),
          };
          // Strict Mode runs effects twice in development; never list one twice.
          setDatasets((all) => (all.some((d) => d.id === sample.id) ? all : [withSavedStyles(sample), ...all]));
        })
        .catch(() => {})
        .finally(() => !controller.signal.aborted && setPending((n) => Math.max(0, n - 1)));
    }
    return () => controller.abort();
  }, [samples]);
  // Until the samples have arrived the list would be empty, which reads as
  // "you have no data" -- so it shows what it is: loading.
  const status = hostStatus === "ready" && pending > 0 && datasets.length === 0 ? "loading" : hostStatus;
  const [section, setSection] = React.useState<Section>("data");
  const [query, setQuery] = React.useState("");
  const [sort, setSort] = React.useState<SortKey>("recent");
  const [view, setView] = useListView();
  const [regStatus, setRegStatus] = React.useState<"active" | "inactive" | "all">("active");
  const [openId, setOpenId] = React.useState<string | null>(null);
  const [importing, setImporting] = React.useState(false);
  const [uploadError, setUploadError] = React.useState<string | null>(null);
  const fileRef = React.useRef<HTMLInputElement>(null);
  const uploads = React.useRef(0);

  const pickFile = () => fileRef.current?.click();

  /** Read in the browser: the file is never sent anywhere. */
  const upload = async (file: File) => {
    setUploadError(null);
    if (file.size > MAX_UPLOAD_BYTES) {
      setUploadError(`That file is ${Math.round(file.size / 1024 / 1024)} MB. The limit here is 50 MB.`);
      return;
    }
    setImporting(true);
    try {
      const result = datasetFromCsv(`upload-${++uploads.current}`, file.name, await file.text());
      if (typeof result === "string") {
        setUploadError(result);
        return;
      }
      setDatasets((all) => [withSavedStyles(result), ...all]);
      setSection("data");
      setQuery("");
      setOpenId(result.id);
      onUpload?.(file, result);
    } catch {
      setUploadError("Couldn't read that file.");
    } finally {
      setImporting(false);
    }
  };

  const open = datasets.find((d) => d.id === openId) ?? null;

  const visible = React.useMemo(() => {
    const q = query.trim().toLowerCase();
    return datasets
      .filter((d) => d.section === section)
      .filter((d) => section !== "regulations" || regStatus === "all" || d.status === regStatus)
      .filter((d) => !q || `${d.title} ${d.description}`.toLowerCase().includes(q))
      .sort((a, b) =>
        sort === "name"
          ? a.title.localeCompare(b.title)
          : sort === "oldest"
            ? a.uploadedAt.localeCompare(b.uploadedAt)
            : b.uploadedAt.localeCompare(a.uploadedAt),
      );
  }, [datasets, section, query, sort, regStatus]);

  return (
    <div
      data-slot="datahub-workspace"
      className={cn(
        // Same envelope as map-workspace, so the docs page does not jump when
        // one block replaces the other.
        "bg-background relative h-[max(480px,75svh)] w-full overflow-auto rounded-xl border border-border md:h-[700px] lg:h-[760px]",
        className,
      )}
    >
      {/* Outside both views so Upload works from the list and from its empty state. */}
      <input
        ref={fileRef}
        type="file"
        accept=".csv,text/csv"
        className="sr-only"
        tabIndex={-1}
        aria-label="Choose a CSV file to upload"
        onChange={(e) => {
          const file = e.target.files?.[0];
          // Reset so choosing the same file again still fires onChange.
          e.target.value = "";
          if (file) void upload(file);
        }}
      />
      {open ? (
        <DatasetDetail
          dataset={open}
          onBack={() => setOpenId(null)}
          saveFailed={saveFailed}
          onChange={(next) => {
            setDatasets((all) => all.map((d) => (d.id === next.id ? next : d)));
            setSaveFailed(!saveStyles(next));
          }}
          onDelete={() => {
            setDatasets((all) => all.filter((d) => d.id !== open.id));
            setOpenId(null);
          }}
        />
      ) : (
        <div className="mx-auto w-full max-w-6xl space-y-4 p-4 md:p-6">
          <header className="flex flex-wrap items-start justify-between gap-x-6 gap-y-3">
            <div className="space-y-1">
              <h2 className="text-xl font-semibold tracking-tight">Data</h2>
              <p className="text-muted-foreground text-sm">Here&apos;s a list of all your data</p>
            </div>
            <Button onClick={pickFile} disabled={importing}>
              <Upload data-icon="inline-start" />
              {importing ? "Importing…" : "Upload data"}
            </Button>
          </header>

          {uploadError ? (
            <Alert variant="destructive">
              <TriangleAlert />
              <AlertTitle>Couldn&apos;t import that file</AlertTitle>
              <AlertDescription>{uploadError}</AlertDescription>
              <AlertAction>
                <Button variant="ghost" size="xs" onClick={() => setUploadError(null)}>
                  Dismiss
                </Button>
              </AlertAction>
            </Alert>
          ) : null}

          <Tabs
            value={section}
            onValueChange={(v) => {
              setSection(v as Section);
              setQuery("");
            }}
          >
            <TabsList>
              {SECTIONS.map(({ id, label, icon: Icon }) => (
                <TabsTrigger key={id} value={id}>
                  <Icon />
                  {label}
                </TabsTrigger>
              ))}
            </TabsList>
          </Tabs>

          <div className="flex flex-wrap items-center gap-2">
            <InputGroup className="min-w-48 flex-1">
              <InputGroupAddon>
                <Search />
              </InputGroupAddon>
              <InputGroupInput
                value={query}
                onChange={(e) => setQuery(e.target.value)}
                placeholder="Search for data"
                aria-label="Search for data"
              />
            </InputGroup>
            {section === "regulations" ? (
              <Select
                value={regStatus}
                onValueChange={(v) => setRegStatus((v ?? "active") as typeof regStatus)}
              >
                <SelectTrigger className="w-28" aria-label="Regulation status">
                  <SelectValue>{(v: string) => v.charAt(0).toUpperCase() + v.slice(1)}</SelectValue>
                </SelectTrigger>
                <SelectContent>
                  <SelectItem value="active">Active</SelectItem>
                  <SelectItem value="inactive">Inactive</SelectItem>
                  <SelectItem value="all">All</SelectItem>
                </SelectContent>
              </Select>
            ) : null}
            <Select value={sort} onValueChange={(v) => setSort((v ?? "recent") as SortKey)}>
              <SelectTrigger className="w-36" aria-label="Sort">
                <SelectValue>{(v: string) => SORTS[v as SortKey]}</SelectValue>
              </SelectTrigger>
              <SelectContent>
                {(Object.keys(SORTS) as SortKey[]).map((k) => (
                  <SelectItem key={k} value={k}>
                    {SORTS[k]}
                  </SelectItem>
                ))}
              </SelectContent>
            </Select>
            <ToggleGroup
              variant="outline"
              value={[view]}
              // A group lets its last item be switched off; a list has to be one or the other.
              onValueChange={(next) => next[0] && setView(next[0] as ListView)}
              aria-label="View"
            >
              <ToggleGroupItem value="cards" aria-label="Cards">
                <LayoutGrid />
              </ToggleGroupItem>
              <ToggleGroupItem value="list" aria-label="List">
                <ListIcon />
              </ToggleGroupItem>
            </ToggleGroup>
          </div>

          {status === "loading" ? (
            <div
              role="status"
              aria-label="Loading data"
              className={view === "list" ? "grid gap-2" : "grid gap-4 sm:grid-cols-2 lg:grid-cols-3"}
            >
              {Array.from({ length: 6 }, (_, i) =>
                view === "list" ? <RowSkeleton key={i} /> : <CardSkeleton key={i} />,
              )}
            </div>
          ) : status === "error" ? (
            <Empty className="border">
              <EmptyHeader>
                <EmptyMedia variant="icon">
                  <TriangleAlert />
                </EmptyMedia>
                <EmptyTitle>Couldn&apos;t load your data</EmptyTitle>
                <EmptyDescription>
                  Something went wrong reaching the data hub. Nothing was changed.
                </EmptyDescription>
              </EmptyHeader>
              <EmptyContent>
                <Button variant="outline" onClick={onRetry}>
                  Try again
                </Button>
              </EmptyContent>
            </Empty>
          ) : visible.length === 0 ? (
            <Empty className="border">
              <EmptyHeader>
                <EmptyMedia variant="icon">
                  {query ? <Search /> : <Link2 />}
                </EmptyMedia>
                <EmptyTitle>
                  {query ? "No results" : `No ${section} yet`}
                </EmptyTitle>
                <EmptyDescription>
                  {query
                    ? `Nothing in ${SECTIONS.find((s) => s.id === section)?.label} matches “${query}”.`
                    : "Upload a file to add it to your hub."}
                </EmptyDescription>
              </EmptyHeader>
              <EmptyContent>
                {query ? (
                  <Button variant="outline" onClick={() => setQuery("")}>
                    Clear search
                  </Button>
                ) : (
                  <Button onClick={pickFile} disabled={importing}>
                    <Upload data-icon="inline-start" />
                    Upload data
                  </Button>
                )}
              </EmptyContent>
            </Empty>
          ) : (
            <ul className={view === "list" ? "grid gap-2" : "grid gap-4 sm:grid-cols-2 lg:grid-cols-3"}>
              {visible.map((d) => (
                <li key={d.id} className="flex min-w-0">
                  {view === "list" ? (
                    <DatasetRow dataset={d} onOpen={() => setOpenId(d.id)} />
                  ) : (
                    <DatasetCard dataset={d} onOpen={() => setOpenId(d.id)} />
                  )}
                </li>
              ))}
            </ul>
          )}
        </div>
      )}
    </div>
  );
}

export default DatahubWorkspace;
